export const SEARCH_TEXT_CHANGE = 'SEARCH_TEXT_CHANGE';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SEARCH_MOVIES_MERGE = 'SEARCH_MOVIES_MERGE';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';
//
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE';
//
export const FAVOURITES_REMOVE = 'FAVOURITES_REMOVE';
export const FAVOURITES_TOGGLE = 'FAVOURITES_TOGGLE';
